student:
  channels: 3
norm:
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
augmentations:
  global_1:
  - name: globalcrop
  - name: flip
  - name: colorjitter
    p: 0.8
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.4
  - name: grayscale
    p: 0.2
  - name: blur
    p: 1.0
  global_2:
  - name: globalcrop
  - name: flip
  - name: colorjitter
    p: 0.8
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.4
  - name: grayscale
    p: 0.2
  - name: blur
    p: 0.1
  - name: solarize
    p: 0.2
    threshold: 128
    max_value: 256
  local:
  - name: localcrop
  - name: flip
  - name: colorjitter
    p: 0.8
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.4
  - name: grayscale
    p: 0.2
  - name: blur
    p: 0.5