model:
  model_name_or_path: "facebook/opt-125m"
  freeze_backbone: False
  tune_mm_mlp_adapter: False
  vision_tower: None
  mm_vision_select_layer: -1
  pretrain_mm_mlp_adapter: None
  mm_projector_type: "attn_pool"
  mm_vision_select_feature: "patch"
  mm_vision_config_path: None
  mm_vision_checkpoint_path: None
data:
  root_path: None
  db_name: "CT-RATE_train_reports"
  channels: 10
  data_mean: 0.0
  data_std: 1.0
  is_multimodal: True
  image_tokens: 128
  conv_template: "plain"
train:
  deepspeed: "/path/to/deepspeed.json"
  cache_dir: None
  optim: "adamw_torch"
  freeze_mm_mlp_adapter: False
  model_max_length: 512
  double_quant: True
  quant_type: "nf4"
  bits: 16
  lora_enable: False
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  lora_weight_path: ""
  lora_bias: "none"
  learning_rate: 1e-3
  mm_projector_lr: 1e-4
  group_by_modality_length: False
  report_to: "none"
  log_dir: None
  num_train_epochs: 1
  per_device_train_batch_size: 32
  gradient_accumulation_steps: 1
  eval_strategy: "no"
  save_strategy: "steps"
  save_steps: 24000
  save_total_limit: 1
  weight_decay: 0.0
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  logging_steps: 1
  bf16: True
  tf32: True
  model_max_length: 2048
  gradient_checkpointing: True
  dataloader_num_workers: 4