dino:
    head_n_prototypes: 131072
    head_bottleneck_dim: 384
ibot:
    separate_head: true
    head_n_prototypes: 131072
train:
    grad_accum_steps: 8
    batch_size_per_gpu: 32
    batch_size_full: 3072
    dataset_path: CtCollection:root=./datasets:extra=./datasets/combined/extra:split=TRAIN
    centering: centering
    OFFICIAL_EPOCH_LENGTH: 1000
    print_freq: 40
    saveckp_iterations: 5000
evaluation:
    eval_period_iterations: 10000
student:
    arch: vit_large
    patch_size: 14
    channels: 1
    drop_path_rate: 0.4
    ffn_layer: swiglufused
    block_chunks: 4
    num_register_tokens: 4
    interpolate_antialias: true
    interpolate_offset: 0.0
optim:
    epochs: 300
    weight_decay_end: 0.2
    base_lr: 3.5e-4
    warmup_epochs: 50
    layerwise_decay: 1.0
augmentations:
    crops:
        local_crops_size: 98
    norm:
        mean: 0.124
        std: 0.121
    global_1:
    - rotation_0.8_90
    - crop
    - contrast_0.8_0.4
    - brightness_0.8_0.4
    - blur_1
    global_2:
    - crop
    - contrast_0.8_0.4
    - brightness_0.8_0.4
    - solarize_0.2_0.5_1
    - noise_0.5_0.02_1
    - blur_0.1
    local:
    - crop
    - contrast_0.8_0.4
    - brightness_0.8_0.4
    - blur_0.5