train:
  grad_accum_steps: 8
  batch_size_per_gpu: 64
data:
  datasets:
  - name: LIDC-IDRI
    type: ct
    split: train
    channels: 4
  - name: NSCLC-Radiomics
    type: ct
    split: train
    channels: 4
  - name: NSCLC-Radiogenomics
    type: ct
    split: train
    channels: 4
  - name: DeepRDT-lung
    type: ct
    split: train
    channels: 4
student:
  arch: vit_base
  ffn_layer: "mlp"
  drop_path_rate: 0.1
teacher:
  warmup_teacher_temp_epochs: 20
optim:
  epochs: 50
  warmup_epochs: 10
  base_lr: 0.003
