train:
  grad_accum_steps: 8
  batch_size_per_gpu: 64
data:
  root_path: /home/rmaguado/rdt/DeepRDT/datasets/
  datasets:
    - name: "radiomics_datasets"
      index_path: data/radiomics_datasets.db
      type: "ct"
      options:
        channels: 1
        lower_window: -1000.0
        upper_window: 2000.0
student:
  arch: vit_base
  ffn_layer: "mlp"
  drop_path_rate: 0.1
teacher:
  warmup_teacher_temp_epochs: 20
optim:
  epochs: 50
  warmup_epochs: 10
  base_lr: 0.003
