train:
  batch_size_per_gpu: 32
  grad_accum_steps: 16
  full_image:
    epochs: 5
    batch_size_per_gpu: 8
    grad_accum_steps: 64
student:
  arch: vit_small
  ffn_layer: mlp
  drop_path_rate: 0.0
teacher:
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 80
  warmup_epochs: 10
  base_lr: 0.003
