MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  output_dir: .
  seed: 0
  num_workers: 10
  OFFICIAL_EPOCH_LENGTH: 1000
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
  stage1:
    epochs: 90
    batch_size_total: 2048
    batch_size_per_gpu: 64
    grad_accum_steps: 1
  stage2:
    epochs: 10
    batch_size_total: 2048
    batch_size_per_gpu: 16
    grad_accum_steps: 4
checkpoints:
  print_iterations: 10
  save_checkpoint_iterations: 1000
  save_teacher_iterations: 10000
student:
  arch: vit_large
  patch_size: 14
  full_image_size: 448
  channels: 1
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "swiglu"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 4
  interpolate_antialias: true
  interpolate_offset: 0.0
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 3.5e-4
  lr: 0.
  warmup_epochs: 10
  min_lr: 1.0e-05
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crop_scale:
  - 0.30
  - 0.80
  local_crop_scale:
  - 0.16
  - 0.30
  crop_groups:
    - name: 3d_global_ld
      is_target: true
      target_groups:
      - 3d_global_ld
      size: 112
      num_crops: 1
    - name: 3d_local_ld
      is_target: false
      target_groups:
      - 3d_global_ld
      size: 56
      num_crops: 3
    - name: 2d_global_ld
      is_target: false
      target_groups:
      - 3d_global_ld
      size: 112
      num_crops: 3
    - name: 2d_global_hd
      is_target: true
      target_group:
      - 2d_global_hd
      size: 224
      num_crops: 3
    - name: 2d_local_hd
      is_target: false
      target_group:
      - 3d_global_ld
      - 2d_global_hd
      size: 112
      num_crops: 2
augmentations:
  default_ct:
    3d_global_ld:
      - name: rotate
      - name: globalcrop
      - name: gaussian_blur
        p: 0.5
    3d_local_ld:
      - name: rotate
      - name: localcrop
      - name: gaussian_blur
        p: 0.5
    2d_global_ld:
      - name: slice
      - name: rotate
      - name: globalcrop
      - name: gaussian_blur
        p: 0.5
    2d_global_hd:
      - name: slice
      - name: rotate
      - name: localcrop
      - name: gaussian_blur
        p: 0.5
    2d_local_hd:
      - name: rotate
      - name: globalcrop
      - name: gaussian_blur
        p: 0.5
datasets:
  - name: default_dataset
    weight: 1.0
    root_path: .
    type: ct
    storage: dicom
    augmentation: default_ct
    channels: 1
    pixel_range:
      lower: -1000.0
      upper: 1900.0
    norm:
      mean: -573.8
      std: 461.3