compute_precision: bf16
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  grad_accum_steps: 16
  batch_size_per_gpu: 16
  batch_size_total: 2048
  output_dir: .
  seed: 0
  num_workers: 10
  iterations_per_epoch: 1000
checkpoints:
  print_iterations: 10
  save_checkpoint_iterations: 1000
  save_teacher_iterations: 10000
student:
  model_name: vitl14_2d3d
  pretrained_weights: ''
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4
  embed_layers:
    patch2d:
      patch_size: 14
      img_size: 448
      in_channels: 10
    patch3d:
      patch_size: 14
      img_size: 224
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  ffn_layer: "swiglu"
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 100
  warmup_epochs: 10
  base_lr: 3.5e-4
  min_lr: 1.0e-05
  weight_decay: 0.04
  weight_decay_end: 0.2
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  views:
    enable_3d: true
    enable_2d: true
  crops_number:
    global_2d: 3
    local_3d: 4
    local_2d: 4
    global_view_multiple: 2
  crop_sizes:
    global_3d: 112
    global_2d: 224
    local_3d: 56
    local_2d: 112
    channels: 10
datasets:
  - name: default_dataset
    weight: 1.0
    index_path: .
    type: ct
    storage: dicom
    bounds: [-1000.0, 1900.0] 
    norm:
      mean: -573.8
      std: 461.3