MODEL:
  WEIGHTS: ''
compute_precision: bf16
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  grad_accum_steps: 16
  batch_size_per_gpu: 16
  batch_size_total: 2048
  output_dir: .
  saveckp_iterations: 5000
  print_freq: 100
  seed: 0
  num_workers: 10
  OFFICIAL_EPOCH_LENGTH: 1000
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
evaluation:
  eval_period_iterations: 10000
student:
  patch_size: 14
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4.0
  full_image_size: 448
  channels: 10
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "swiglu"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  embed_layer: "patch"
  conv_channels: 0
  num_register_tokens: 4
  interpolate_antialias: true
  interpolate_offset: 0.0
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 100
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 3.5e-4
  lr: 0.
  warmup_epochs: 10
  min_lr: 1.0e-05
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 98
augmentations:
  default_ct:
    global_1:
    - name: rotate
      p: 0.8
    - name: globalcrop
    - name: flip
      p: 0.5
    - name: gaussian_blur
      p: 1.0
    global_2:
    - name: globalcrop
    - name: flip
      p: 0.5
    - name: noise
      p: 0.5
      mean: 0.0
      std: 0.1
    - name: gaussian_blur
      p: 0.1
    local:
    - name: localcrop
    - name: flip
      p: 0.5
    - name: gaussian_blur
      p: 0.5
datasets:
  - name: default_dataset
    weight: 1.0
    index_path: .
    type: ct
    storage: dicom
    augmentation: default_ct
    pixel_range:
      lower: -1000.0
      upper: 1900.0
    norm:
      mean: -573.8
      std: 461.3