compute_precision:
  teacher:
    backbone:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
    dino_head:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
    ibot_head:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
  student:
    backbone:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
    dino_head:
      param_dtype: fp16
      reduce_dtype: fp32
      buffer_dtype: fp32
    ibot_head:
      param_dtype: fp16
      reduce_dtype: fp32
      buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  output_dir: .
  seed: 0
  num_workers: 10
  iterations_per_epoch: 1000
  centering: "centering"
  epochs: 100
  batch_size_total: 2048
  batch_size_per_gpu: 64
  grad_accum_steps: 1
checkpoints:
  print_iterations: 10
  save_checkpoint_iterations: 1000
  save_teacher_iterations: 10000
student:
  model_name: vitl14_2d3d
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4
  embed_layers:
  - type: patch2d
    patch_size: 14
    img_size: 448
    in_channels: 1
  - type: patch3d
    patch_size: 14
    img_size: 224
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "swiglu"
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  base_lr: 3.5e-4
  min_lr: 1.0e-06
  weight_decay: 0.04
  weight_decay_end: 0.2
  warmup_epochs: 10
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crop_scale:
  - 0.30
  - 0.80
  local_crop_scale:
  - 0.16
  - 0.30
transform_groups:
  - name: 3d_global_ld
    size: 112
    num_crops: 1
    embed_layer: patch3d
    is_target: true
    targets:
      - 3d_global_ld
    transforms:
      - name: globalcrop3d
      - name: transpose3d
      - name: flip3d
      - name: gaussian_blur
        p: 0.5
  - name: 3d_local_ld
    size: 56
    num_crops: 3
    embed_layer: patch3d
    targets:
      - 3d_global_ld
    transforms:
    - name: localcrop3d
    - name: transpose3d
    - name: flip3d
    - name: gaussian_blur
      p: 0.5
  - name: 2d_global_hd
    size: 224
    num_crops: 3
    embed_layer: patch2d
    is_target: true
    targets:
      - 3d_global_ld
      - 2d_global_hd
    transforms:
      - name: slice
        n_slices: 1
      - name: rotate
      - name: localcrop2d
      - name: gaussian_blur
        p: 0.5
  - name: 2d_local_hd
    size: 112
    num_crops: 2
    embed_layer: patch2d
    targets:
      - 2d_global_hd
      - 3d_global_ld
    transforms:
      - name: rotate
      - name: globalcrop2d
      - name: gaussian_blur
        p: 0.5
augmentations:
  default_3d:
    - name: 3d_global_ld
      subgroups:
        - name: 3d_local_ld
        - name: 2d_global_hd
          subgroups: 
            - name: 2d_local_hd
datasets:
  - name: default_dataset
    weight: 1.0
    index_path: .
    type: ct
    storage: dicom
    augmentation: default_3d
    pixel_range:
      lower: -1000.0
      upper: 1900.0
    norm:
      mean: -573.8
      std: 461.3